services:
  # 1. Le Backend (Laravel via Docker)
  - type: web
    name: bambadiante-backend
    env: docker
    dockerfilePath: ./backend/docker/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:g/ziyIjNp6G6TIKb1kgO38yHKyKUH4y39BqWEcE6L8M=
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /backend/database/database.sqlite
      - key: SANCTUM_STATEFUL_DOMAINS
        value: bambadiante-frontend.onrender.com
      - key: FRONTEND_URL
        value: https://bambadiante-frontend.onrender.com

# 2. Le Frontend (React en site statique)
  - type: web
    name: bambadiante-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://bambadiante-backend.onrender.com