services:
  # 1. Le Backend (Laravel)
  - type: web
    name: bambadiante-backend
    env: docker
    dockerfilePath: ./backend/docker/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: APP_NAME
        value: BambaDiante
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:g/ziyIjNp6G6TIKb1kgO38yHKyKUH4y39BqWEcE6L8M=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://bambadiante-backend.onrender.com
      - key: FRONTEND_URL
        value: https://bambadiante.onrender.com
      - key: SANCTUM_STATEFUL_DOMAINS
        value: bambadiante.onrender.com
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_ENCRYPT
        value: "false"
      - key: SESSION_PATH
        value: /
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: bambadiante-db
          property: connectionString

  # 2. Le Frontend (React en site statique)
  - type: web
    name: bambadiante
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://bambadiante-backend.onrender.com

databases:
  - name: bambadiante-db
    plan: free
    databaseName: bambadiante
    user: bambadiante